In [1]:
import numpy as np
import pandas as pd

Numpy one- and multi dimensional array creation

In [2]:
a = np.array([1,2,3,4])
print(a)

a1 = np.array([1,2,3,4], dtype="float")
print(a1)

a2=np.ones(3, dtype=int)
print(a2)

a3=np.zeros((2, 4), dtype=float)
print(a3)

a4=np.linspace(0, 5, 5)
print(a4)

a5=np.random.random((4, 3))
print(a5)

a6=np.random.randint(0, 100, (4, 4))
print(a6)

b=np.array([[1,2,4,5], [5,6,7,8], [9,10,11,12]])
print(b)


[1 2 3 4]
[1. 2. 3. 4.]
[1 1 1]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0.   1.25 2.5  3.75 5.  ]
[[0.89407236 0.40939276 0.96911824]
 [0.43702648 0.87551847 0.09368388]
 [0.0075723  0.57279908 0.14244001]
 [0.72143008 0.87211726 0.7719924 ]]
[[58 28 12 50]
 [41 41 50 15]
 [43 58 49 76]
 [29 63  1  9]]
[[ 1  2  4  5]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Indexes

In [3]:
print(a1[0])

print(a1[-1])
print(a1[-2])

print(a6[0])
print(a6[0][0])

1.0
4.0
3.0
[58 28 12 50]
58


Selections

In [4]:

array=np.random.randint(0, 100, 10)
print(array)
selected_array=array[0:5:1]
print(selected_array)

array[2]=1000
print(array)
print(selected_array)



[21 56 24 11 64 14 29 51 82 26]
[21 56 24 11 64]
[  21   56 1000   11   64   14   29   51   82   26]
[  21   56 1000   11   64]


In [5]:
array_matrix=np.random.randint(0, 100, (4, 4))
print(array_matrix)

selected_matrix=array_matrix[0:2, 0:2]
print(selected_matrix)

[[81  0 26 78]
 [28 47  6 18]
 [81 14  9 85]
 [63 59 69 49]]
[[81  0]
 [28 47]]


Arithmetic operations

In [6]:
operated_array=np.random.randint(0, 100, 16)
print(operated_array)

operated_array=operated_array*2
print(operated_array)

operated_array=operated_array+3
print(operated_array)

operated_array=operated_array//2
print(operated_array)


[90 17 17 42 65 17 14 81 62 88 94  6  4 47 25 19]
[180  34  34  84 130  34  28 162 124 176 188  12   8  94  50  38]
[183  37  37  87 133  37  31 165 127 179 191  15  11  97  53  41]
[91 18 18 43 66 18 15 82 63 89 95  7  5 48 26 20]


Reduce etc.

In [7]:
a10 = np.arange(0, 6)
print(a10)

print(np.add.reduce(a10))
#bollean_array = [True, True, True, True, True]
print(np.add.accumulate(a10))

x = np.array(['a', 'b', 'c'], dtype=object)
np.outer(x, [1, 2, 3])


[0 1 2 3 4 5]
15
[ 0  1  3  6 10 15]


array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

Data from .csv file

In [8]:
data = pd.read_csv('iris.csv')
petal = np.array(data['petal_length'])

print("Sum: ", np.sum(petal))
print("Min: ", np.min(petal))
print("Max: ", np.max(petal))
print("Average: ", np.mean(petal))
print("Standart Deviation: ", np.std(petal))
print("Dispesion: ", np.var(petal))
print("Mediana: ", np.median(petal))
print("Percentile: ", np.percentile(petal, 50))

Sum:  563.8
Min:  1.0
Max:  6.9
Average:  3.758666666666666
Standart Deviation:  1.7585291834055212
Dispesion:  3.092424888888889
Mediana:  4.35
Percentile:  4.35
